### ISSUE TITLE
Option to use cdn links rather than actual jars

### ISSUE THREAD

**Issue by Enalmada** [webjars/webjars-play#13]
Webjars project looks really cool.  The ability to manage client-side dependencies in JVM-based web applications seems invaluable. Now that I know about it I feel like I must have it.

But up to this point, I have thought best practice is to use google cdn for all third party libraries possible (https://developers.google.com/speed/libraries/devguide).  Main benefits of using 3rd party CDN being increased download parallelism, chance that users already have the common javascript in their browser cache, free bandwidth.

I wonder if webjars project could offer the best of both worlds by using cdn urls rather than actual jars?

**Comment by wsargent** [comment]
Would it be possible to use subresource integrity links when using CDNs in webjars?  I'm not quite sure how we'd work out the hashes automatically, but it would add an extra level of security.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by jamesward** [comment]
@wsargent That'd be cool.  Are you thinking we put the hashes into the WebJar somewhere and then have the WebJars Locator pull them out?
