### ISSUE TITLE
Webjars 2.8.18 Dependency Problem: org.webjars.npm which-collection -> is-set 2.0.3 missing on Maven Central

### ISSUE THREAD

**Issue by HenningHeinz** [webjars/webjars-play#181]
Hello, 
org.webjars.npm which-collection has been updated on September 3th to V1.0.2. 

Its dependencies seem to require V2.0.3 of org.webjars.npm is-set
```
<dependency>
<groupId>org.webjars.npm</groupId>
<artifactId>is-set</artifactId>
<version>[2.0.3,3.0.0-0)</version>
</dependency> 
```
Unfortunately V.2.0.3 is not published on Maven Central which causes an error while building my Play project.

 [error] (update) sbt.librarymanagement.ResolveException: Error downloading org.webjars.npm:is-set:[2.0.3,3)
[error]   No version found for [2.0.3,3) 

unfortunately I have no clue how to fix this. 

Kindest Regards

Henning

Update: I now have added 2.0.3 manually locally at 
~/.cache/coursier/v1/https/repo1.maven.org/maven2/org/webjars/npm/is-set/2.0.3/ 
which at least results in my Play application starting again.

**Comment by jamesward** [comment]
I've deployed the `is-set` NPM WebJar via https://webjars.org and it should be available on Maven Central in a few hours.  In the future you should be able to deploy missing dependencies like this on your own via https://webjars.org
Let me know if you have any further issues!
