### ISSUE TITLE
Add documentation to help debug when `NoSuchFieldException` is thrown in `nastyReflectedRoute`

### ISSUE THREAD

**Issue by metasim** [webjars/webjars-play#62]
When `NoSuchFieldException` is thrown in `nastyReflectedRoute`, it would be helpful to point to some documentation on what needs to be done to the `routes` file to fix it.

**Comment by jamesward** [comment]
Let me know what you think about: https://github.com/webjars/webjars-play/compare/fix/better-route-error

**Comment by metasim** [comment]
Yes! Huge help! Thank you for doing that!

**Comment by jamesward** [comment]
This will be released shortly as `2.5.0-2`.
