### ISSUE TITLE
 not found: value WebJarAssets after migrating from Play 2.4 to Play 2.5

### ISSUE THREAD

**Issue by Bunyod** [webjars/webjars-play#64]
I've issue after migrating from Play 2.4 to Play 2.5. For example: 
`<script src="@routes.WebJarAssets.at(WebJarAssets.locate("knockout.js"))"></script>`

Changes in build.sbt:
`"org.webjars" % "webjars-play_2.11" % "2.4.0-1"`
to
`"org.webjars" %% "webjars-play" % "2.5.0"`

 As far as I understand, In order to use some external lib, now we should inject WebJarAssets and RequireJS dependencies everywhere. I think would be better remain as they are.

**Comment by jamesward** [comment]
In the simplest form you don't need to do anything to special to use WebJars in Play 2.5.  The libs are available via the regular static assets path.  So if you have this route:

    GET         /assets/*file           controllers.Assets.at(path="/public", file)

And for instance have the Bootstrap WebJar then the css will be available at:

    /assets/lib/bootstrap/css/bootstrap.css

If you want to use `webjars-play` then you need a new route:

    GET     /webjars/*file                    controllers.WebJarAssets.at(file)

And you need to inject `WebJarAssets` into your Controller and then pass a reference to the template.

If you want to use RequireJS you can but it isn't necessary.

This is all in the doc: http://www.webjars.org/documentation

Let me know if there needs to be more info in there to make this more clear.
