### ISSUE TITLE
support play 2.6

### ISSUE THREAD

**Issue by xuwei-k** [webjars/webjars-play#66]

**Comment by jamesward** [comment]
See #67 

Let me know what you think.

**Comment by mslinn** [comment]
Looking forward to this release!

**Comment by gslowikowski** [comment]
Publish `2.6.0-M1` to Maven central repo, please.

**Comment by jamesward** [comment]
Publishing now.  Sorry about that.  I uploaded the artifacts but forgot to actually publish them.
