### ISSUE TITLE
Obfuscating the WebJarAssets injection and template variables.

### ISSUE THREAD

**Issue by Busti** [webjars/webjars-play#68]
When using templates I usually use the locate method in my base template to add javascripts and stylesheets.  
To do so efficiently I have to pass the webJarAssets variable through all templates that render within my base template.
I also have to call the view with the webJarAssets variable every time I want to render a template.

Controller:

    Ok(views.html.index(webJarAssets))

Index View:

    @(webJarAssets: WebJarAssets)(implicit messages: Messages)
    
    @base(webJarAssets, "Title") {
        <h1>Content</h1>
    }

Base View:

    @(webJarAssets: WebJarAssets, title: String)

    <!DOCTYPE html>

    <html>
        <head>
            <title>@title</title>
    
            <script src="@routes.WebJarAssets.at(webJarAssets.locate("jquery.min.js"))" type="text/javascript"></script>
        </head>
        <body>
        @content
        </body>
    </html>`

Is it possible to get rid of the webJarAssets variable in my views and controller call so that it is only present in the base view?

Maybe implicitly passing the injection through to the base template?

**Comment by jamesward** [comment]
The best way to do this is with Twirl template injection.  I do that on webjars.org so you can see how with these:
https://github.com/webjars/webjars/blob/master/app/views/main.scala.html#L1
https://github.com/webjars/webjars/blob/master/build.sbt#L11
https://github.com/webjars/webjars/blob/master/project/plugins.sbt#L8

In Play 2.6 I think this becomes a standard feature.

I hope that helps.

**Comment by Busti** [comment]
Adding the plugin and Injection stops my templates from compiling correctly.
Calls like `@HtmlFormat.empty` stop working unless imported and referencing other templates withing a template stops working completely.

Is there something I am missing?

**Comment by jamesward** [comment]
Hmmm.. Maybe there was a settings change or something with the new version of Twirl.
