### ISSUE TITLE
Version 2.6.0 for Scala 2.11 not published

### ISSUE THREAD

**Issue by gslowikowski** [webjars/webjars-play#72]
There is `2.6.0` version [for Scala 2.12](http://repo1.maven.org/maven2/org/webjars/webjars-play_2.12/) published to Maven central, but not [for Scala 2.11](http://repo1.maven.org/maven2/org/webjars/webjars-play_2.11/).

**Comment by jamesward** [comment]
Thanks for the heads up!  I'm releasing that now.
