### ISSUE TITLE
webjars-play not working java project

### ISSUE THREAD

**Issue by EdozdeDandez** [webjars/webjars-play#89]
Hi I'm having a problem using webjars-play on a newly created play JAVA project 2.7.3.
I have changed the routes and the build.sbt files as required and downloaded it but incorporating it in the view files is a problem if I put the line at the very top of the main.scala.html page as follows:
`
@this(webJarUtil: org.webjars.play.WebJarsUtil)
@*
 * This template is called from the `index` template. This template
 * handles the rendering of the page header and body tags. It takes
 * two arguments, a `String` for the title of the page and an `Html`
 * object to insert into the body of the page.
 *@
@(title: String)(content: Html)
<!DOCTYPE html>
<html lang="en">
    <head>
        @* Here's where we render the page title `String`. *@
        <title>@title</title>
        @webJarUtil.locate("bootstrap.min.css").css()
        <link rel="stylesheet" media="screen" href="@routes.Assets.versioned("stylesheets/main.css")">
        <link rel="shortcut icon" type="image/png" href="@routes.Assets.versioned("images/favicon.png")">
    </head>
    <body>
        @* And here's where we render the `Html` object containing
         * the page content. *@
        @content

        @webJarUtil.locate("jquery.min.js").script()
        @webJarUtil.locate("bootstrap.min.js").script()
        @webJarUtil.requireJs(routes.Assets.versioned("javascripts/index.js"))
        
    </body>
</html>
`
I get the error : 

_
not found: value main
`
@main("Welcome to Play") { 
<h1>Welcome to Play!</h1>
}
`
_
If I move the webJarUtil line down as follows:
`
@(title: String)(content: Html)
@this(webJarUtil: org.webjars.play.WebJarsUtil)
<!DOCTYPE html>
<html lang="en">
    <head>
        @* Here's where we render the page title `String`. *@
        <title>@title</title>
        @webJarUtil.locate("bootstrap.min.css").css()
        <link rel="stylesheet" media="screen" href="@routes.Assets.versioned("stylesheets/main.css")">
        <link rel="shortcut icon" type="image/png" href="@routes.Assets.versioned("images/favicon.png")">
    </head>
    <body>
        @* And here's where we render the `Html` object containing
         * the page content. *@
        @content

        @webJarUtil.locate("jquery.min.js").script()
        @webJarUtil.locate("bootstrap.min.js").script()
        @webJarUtil.requireJs(routes.Assets.versioned("javascripts/index.js"))
        
    </body>
</html>
`
I get the error: 

_
not found: value webJarUtil
`
@this(webJarUtil:` org.webjars.play.WebJarsUtil)
`
_

build.sbt

`
name := """my-first-play-project"""
organization := "com.example"
version := "1.0-SNAPSHOT"
lazy val root = (project in file(".")).enablePlugins(PlayJava)
scalaVersion := "2.13.0"
libraryDependencies += guice
libraryDependencies ++= Seq(
"org.webjars" %% "webjars-play" % "2.7.3",
    "org.webjars" % "bootstrap" % "4.3.1" exclude("org.webjars", "jquery"),
    "org.webjars" % "jquery" % "3.4.1",
    "org.webjars" % "jquery-ui" % "1.12.1",
    "org.webjars" % "font-awesome" % "5.9.0",
)
`

routes

`
# Routes
# This file defines all application routes (Higher priority routes first)
# ~~~~

# An example controller showing a sample home page
GET     /                           controllers.HomeController.index
# My pages

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)

# WebJars
->          /webjars                webjars.Routes
`

What am I doing wrong?

**Comment by jamesward** [comment]
I'm having a hard time following what is going on due to formatting.  Did you restart the build after updating the `build.sbt` file?

**Comment by EdozdeDandez** [comment]
Yes I restarted it.

**Comment by EdozdeDandez** [comment]
1. bild.sbt
![Screen Shot 2019-08-06 at 21 14 33](https://user-images.githubusercontent.com/19285317/62565341-4214bc00-b88f-11e9-98df-7de82871edc8.png)

2. main.scala.html with webjarutil declaration at the top
![Screen Shot 2019-08-06 at 21 14 12](https://user-images.githubusercontent.com/19285317/62565342-4214bc00-b88f-11e9-8c75-ad8a7954dae1.png)

3. main.scala.html with webjarutil declaration just before the doctype
![Screen Shot 2019-08-06 at 21 13 48](https://user-images.githubusercontent.com/19285317/62565343-42ad5280-b88f-11e9-9617-0182f7f3722b.png)

4. routes
![Screen Shot 2019-08-06 at 21 13 07](https://user-images.githubusercontent.com/19285317/62565345-4345e900-b88f-11e9-9f5e-b08f97be5eaf.png)

5. index.scala.html
![Screen Shot 2019-08-06 at 21 19 07](https://user-images.githubusercontent.com/19285317/62565614-d97a0f00-b88f-11e9-97d9-2d7cee993d35.png)

Putting the declaration at the top of the main.scala.html gives the error- not found: value main
Putting the declaration just before the doctype of the main.scala.html gives the error- not found: value webJarUtil

**Comment by EdozdeDandez** [comment]
I hope it's clear now

**Comment by jamesward** [comment]
Oh! I see.  The problem is that if you do injection into a template, then to use that template you must inject it, so in `index.scala.html` do:
```
@this(webJarsUtil: org.webjars.play.WebJarsUtil, main: main)
```

For reference see:
https://github.com/webjars/webjars/blob/master/app/views/index.scala.html

**Comment by EdozdeDandez** [comment]
Thanks a lot. Will try that
