### ISSUE TITLE
[Play 2.7.3] Error: "value WebJarAssets is not a member of object controllers.routes"

### ISSUE THREAD

**Issue by mslinn** [webjars/webjars-play#90]
I am using Scala 2.12.10, sbt 1.3.2, Play 2.73 on Ubuntu on Windows 10.

Yay! Pictures!

![webjarCompilation](https://user-images.githubusercontent.com/485818/65841310-b4c17700-e2d5-11e9-9081-0bd2b846b549.png)

![webjarCompilation2](https://user-images.githubusercontent.com/485818/65841322-ce62be80-e2d5-11e9-8322-37d670acc6bb.png)

Does `build.sbt` look right?
```
libraryDependencies ++= Seq(
  cacheApi,
  "com.typesafe.akka" %% "akka-slf4j"   % "2.5.23"  withSources(),
  "javax.inject"      %  "javax.inject" % "1"       withSources(),
  "org.webjars"       %% "webjars-play" % "2.7.3"   withSources(),
  "org.webjars"        % "bootstrap"    % "3.3.7-1" withSources(),
  "net.codingwell"    %% "scala-guice"  % "4.2.6"   withSources(),
  //
  "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.3" % Test
)
```
Might my `routes` file be the problem?
```
GET  /webjars/*file  org.webjars.play.WebJarAssets.at(file)
```

Thanks,
Mike

![mikeSaxMikeDjembe_500](https://user-images.githubusercontent.com/485818/65841451-264df500-e2d7-11e9-8007-c5e873c6dd9b.jpg)

**Comment by jamesward** [comment]
Thanks Mike!  Looking great.  :)

A while back we changed the API to be more injection friendly.  Changes shouldn't be too hard to migrate to:
https://www.webjars.org/documentation

Let me know if any questions come up.  And yeah, we *should* have a migration doc.

**Comment by mslinn** [comment]
Migration done: https://github.com/mslinn/play27-template
The public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)) library is a template for Play 2.7 webapps. It includes working examples of WebJars. Please tell the world :)

**Comment by jamesward** [comment]
Awesome!  Thanks Mike.
